name: Deploy on release

on:
  push:
    tags:
      - "[0-9]*"
      - "test*"
    branches:
      - "ci-test"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: echo "GITHUB_TAG=$(git describe --always --tags)" >> $GITHUB_ENV

      - if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: echo "OS_SHORT_NAME=linux" >> $GITHUB_ENV

      - if: ${{ startsWith(matrix.os, 'macos') }}
        run: echo "OS_SHORT_NAME=macos" >> $GITHUB_ENV

      - if: ${{ startsWith(matrix.os, 'windows') }}
        run: echo "OS_SHORT_NAME=windows" >> $GITHUB_ENV

      - if: ${{ env.OS_SHORT_NAME == 'linux' }}
        run: |
          sudo apt-get install --yes musl-tools
          sudo apt-get install --yes libsqlite3-dev
          sudo apt-get install --yes io_uring

      - name: Set up OCaml for Linux
        uses: ocaml/setup-ocaml@v3
        if: ${{ env.OS_SHORT_NAME == 'linux' }}
        with:
          ocaml-compiler: "ocaml-variants.5.2.1+options,ocaml-option-static"

      - name: Set up OCaml for macOS
        uses: ocaml/setup-ocaml@v3
        if: ${{ env.OS_SHORT_NAME == 'macos' }}
        with:
          ocaml-compiler: "5.2.1"

      - run: opam install dune

      - run: opam install . --deps-only --with-test

      - name: Create build
        if: ${{ env.OS_SHORT_NAME == 'macos' }}
        run: |
          opam exec -- make release-build

      - name: Create static build
        if: ${{ env.OS_SHORT_NAME == 'linux' || env.OS_SHORT_NAME == 'windows' }}
        run: |
          opam exec -- make release-static-build

      - name: Package into tar.gz
        run: |
          mv release/docfd docfd
          tar -cvzf docfd-${{ env.GITHUB_TAG }}-${{ env.OS_SHORT_NAME }}.tar.gz docfd

      - name: Upload artifacts
        if: ${{ github.ref_name == 'ci-test' }}
        uses: actions/upload-artifact@v4
        with:
          name: docfd-${{ env.GITHUB_TAG }}-${{ env.OS_SHORT_NAME }}.tar.gz
          path: docfd-${{ env.GITHUB_TAG }}-${{ env.OS_SHORT_NAME }}.tar.gz

      - name: Release
        if: ${{ github.ref_name != 'ci-test' }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            docfd-${{ env.GITHUB_TAG }}-${{ env.OS_SHORT_NAME }}.tar.gz
